config/routes.rb
Rails.application.routes.draw do

  resources :announcements

  get 'pages/home'

  get 'pages/tithing'

  resources :events

  resources :charges

  resources :audio

  root 'pages#home'

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base

	validates :title, presence: true
end

app/models/audio.rb
class Audio < ActiveRecord::Base

	 has_attached_file :music, 
	 										storage: :s3, 
	 										:s3_credentials => "#{Rails.root}/config/application.yml"

	 validates_attachment_content_type :music, :content_type => ['audio/mpeg']

end

app/models/charge.rb
class Charge < ActiveRecord::Base

  validates :amount, numericality: { greater_than_or_equal_to: 0.49 }

end

app/models/event.rb
class Event < ActiveRecord::Base

	validates :name, uniqueness: true, presence: true, length: { maximum: 50 }

	validates :description, presence: true, length: { maximum: 500,
    too_long: "%{count} characters is the maximum allowed" }

  validates :location, presence: true, length: { maximum: 50 }

  has_attached_file :image, :styles => { :medium => "300x300>", 
  	:thumb => "100x100>" }, 
  	:default_url => "/images/:style/missing.png"

  validates_attachment_content_type :image, :content_type => { :content_type => ["image/jpeg", "image/gif", "image/png"] }
  
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :set_announcement, only: [:show, :edit, :update, :destroy]

  # GET /announcements
  # GET /announcements.json
  def index
    @announcements = Announcement.all
  end

  # GET /announcements/1
  # GET /announcements/1.json
  def show
  end

  # GET /announcements/new
  def new
    @announcement = Announcement.new
  end

  # GET /announcements/1/edit
  def edit
  end

  # POST /announcements
  # POST /announcements.json
  def create
    @announcement = Announcement.new(announcement_params)

    respond_to do |format|
      if @announcement.save
        format.html { redirect_to @announcement, notice: 'Announcement was successfully created.' }
        format.json { render :show, status: :created, location: @announcement }
      else
        format.html { render :new }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /announcements/1
  # PATCH/PUT /announcements/1.json
  def update
    respond_to do |format|
      if @announcement.update(announcement_params)
        format.html { redirect_to @announcement, notice: 'Announcement was successfully updated.' }
        format.json { render :show, status: :ok, location: @announcement }
      else
        format.html { render :edit }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1
  # DELETE /announcements/1.json
  def destroy
    @announcement.destroy
    respond_to do |format|
      format.html { redirect_to announcements_url, notice: 'Announcement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_announcement
      @announcement = Announcement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def announcement_params
      params.require(:announcement).permit(:title, :description, :date)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


end

app/controllers/audio_controller.rb
class AudioController < ApplicationController
   before_action :set_audio, only: [:show, :edit, :update, :destroy]

	def index
		@audio = Audio.all
	end

	def create
  	@audio = Audio.create(audio_params)

  	respond_to do |format|
      if @audio.save
        format.html { redirect_to @audio, notice: 'Audio was successfully created.' }
        format.json { render :show, status: :created, location: @audio }
      else
        format.html { render :new }
        format.json { render json: @audio.errors, status: :unprocessable_entity }
      end
    end
  end

	def new
		@audio = Audio.new
	end

	def show
		@audio = Audio.find(params[:id])
	end

	def edit
	end

	def update
    respond_to do |format|
      if @audio.update(audio_params)
        format.html { redirect_to @audio, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @audio }
      else
        format.html { render :edit }
        format.json { render json: @audio.errors, status: :unprocessable_entity }
      end
    end
  end

	# DELETE /audios/1
  # DELETE /audios/1.json
  def destroy
  	 if @audio.present?
    @audio.destroy
    respond_to do |format|
      format.html { redirect_to @audio, notice: 'Audio was successfully destroyed.' }
      format.json { head :no_content }
    end
    end
  end

	private

	# Use strong_parameters for attribute whitelisting
	# Use callbacks to share common setup or constraints between actions.
    def set_audio
      @audio = Audio.find(params[:id])
    end

	def audio_params
	  params.require(:audio).permit(:music)
	end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

	def new
	end

	def create
		
		token = params[:stripeToken]

    amount = params[:amount].to_f * 100

    if amount < 50
      @error = "Please enter an amount more than 50 cents please."
      render :new
      return
    end

		begin
      charge = Stripe::Charge.create(
        amount:      amount.to_i,
        currency:    "usd",
        card:        token,
        description: "Tithes"
      )

      email = params[:email]  

    rescue Stripe::CardError => e
      # The card has been declined or
      # some other error has occurred
      @error = e
      render :new
    end
  end

	private

		def charge_params
			params.require(:charge).permit(:amount)
		end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :date, :time, :description, :image, :location)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  	@events = Event.order("created_at DESC").limit(6)
  	@announcements = Announcement.order("created_at DESC").limit(1)
  end

  def tithing
  end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/audio_helper.rb
module AudioHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/announcements/_form.html.erb
<%= form_for(@announcement) do |f| %>
  <% if @announcement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>

      <ul>
      <% @announcement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, placeholder: "Mtoher's day show at Asbury Broadneck" %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :date %>
    <%= f.text_field :date, placeholder: "Date of the announcement", id: "datepicker" %>
  </div>
  <div class="actions">
    <%= f.submit "Create announcement", class: "btn-submit" %>
  </div>
<% end %>

app/views/announcements/edit.html.erb
<div class="container">

<h1>Editing Announcement</h1>

<%= render 'form' %>

<%= link_to 'Show', @announcement %> |
<%= link_to 'Back', announcements_path %>

</div>

app/views/announcements/index.html.erb
<div class="container">

  <p id="notice"><%= notice %></p>

  <h1>Listing Announcements</h1>
    
      <% @announcements.each do |announcement| %>
        <div class="announcement-section">
          <div class="annoucement-index-title"><%= announcement.title %></div>
          <div class="ann-index-description"><%= announcement.description %></div>
          <div class="ann-index-date"><%= announcement.date %></div>
          <div>
            <%= link_to 'Show', announcement %> |
            <%= link_to 'Edit', edit_announcement_path(announcement) %> |
            <%= link_to 'Destroy', announcement, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
      <% end %>

  <br>

  <%= link_to 'New Announcement', new_announcement_path %>

</div>

app/views/announcements/new.html.erb
<div class="container">

<h1 class="section-title">New Announcement</h1>

<%= render 'form' %>

<%= link_to 'Back', announcements_path %>

</div>

app/views/announcements/show.html.erb
<div class="container">


	<div>
	  <div class="announcement-title"><%= @announcement.title %></div>

	  <%= @announcement.description %>

	  <%= @announcement.date %>
	</div>


	<div>
		<%= link_to 'Edit', edit_announcement_path(@announcement) %> |
		<%= link_to 'Back', announcements_path %>
	</div>

</div>

app/views/audio/index.html.erb
<div class="container">

  <h1 class="section-title">Sermons</h1>

  <% @audio.each do |audio| %>

    <div class="field">
      <%= audio.music_file_name %>
    </div>

    <div class="field">
      <%= audio_tag audio.music.url, :controls => true %>
    </div>

    <%= link_to 'Show', audio %> |
    <%= link_to 'Edit', edit_audio_path(audio) %> |
    <%= link_to 'Destroy', audio, method: :delete, data: { confirm: 'Are you sure?' } %>

  <% end %>

</div>

app/views/audio/new.html.erb
<%= form_for @audio, :html => { :multipart => true } do |form| %>
  <%= form.file_field :music %>
  <%= submit_tag "Upload" %>
<% end %>

app/views/audio/show.html.erb
<div class="container">
	<h1>Show music</h1>
	<p><%= @audio.music_file_name %></p>
	<div><%= audio_tag @audio.music.url, :controls => true %></div>
</div>

app/views/charges/_form.html.erb
<%= form_tag charges_path, id: 'payment-form' do %>
  <input type="integer" name="amount" id="custom-donation-amount"  placeholder="$100" />

  <button id="customButton" class="btn-submit tithe-btn" "data-no-turbolink" >Process Tithe</button>
<% end %>

<script>
  var handler = StripeCheckout.configure({
    key: 'pk_test_k0yr7cNdCaxLrQgAZtf0LRe5',
    image: '/square-image.png',
    token: function(response) {
    

      var $form = $('#payment-form');

      if (response.error) {
        // Show the errors on the form
        alert(response.error.message);
       // $form.find('button').prop('disabled', false);
      } else {
        // response contains id and card, which contains additional card details
        var token = response.id;
        // Insert the token into the form so it gets submitted to the server
        $form.append($('<input type="hidden" name="stripeToken" />').val(token));
        // $form.append($('<input type="hidden" name="email" />').val(response.email));
        // and submit
        $form.get(0).submit();
      }


      // Use the token to create the charge with a server-side script.
      // You can access the token ID with `token.id`
    }
  });

  $('#customButton').on('click page:change', function(e) {
     e.preventDefault();
    var amount = parseFloat($('#custom-donation-amount').val());
    if (amount < 0.50) {
      alert('Sorry, it must be more than 50 cents.');
      return;
    }
    // Open Checkout with further options
    handler.open({
      name: 'Asbury Broadneck UMC',
      description: 'Tithes',
      amount: amount * 100
    });
   
  });

  // Close Checkout on page navigation
  $(window).on('popstate', function() {
    handler.close();
  });
</script>

app/views/charges/create.html.erb
<div class="container">

	<h1>Thanks</h1>

	<p>Your tithing was processed and is appreciated</p>

	<p><%= link_to "Home", new_charge_path %></p>

</div>

app/views/charges/new.html.erb
<div class="container">
	<div class="tithe-form">

		<h1>Thank you for tithing</h1>

		<p><%= @error %></p>

		<%= render "form" %>


	</div>
</div>

app/views/events/_form.html.erb
<%= form_for @event, :html => { :multipart => true }  do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: "Name of event" %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, placeholder: "Event description" %>
  </div>
  <div class="field">
    <%= f.label :date %>
    <%= f.text_field :date, placeholder: "Date of the event", id: "datepicker" %>
  </div>
  <div class="field">
    <%= f.label :time %>
    <%= f.text_field :time, placeholder: "Time of the event", id: "timepicker" %>
  </div>
  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location, placeholder: "Location name" %>
  </div>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  
  <div class="actions">
    <%= f.submit "Create event", class: "btn-submit" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<section class="container">
  <div class="events">

		<h1 class="section-title">Editing Event</h1>

		<%= render 'form' %>

		<%= link_to 'Show', @event %> |
		<%= link_to 'Back', events_path %>

	</div>
</section>

app/views/events/index.html.erb
<section class="events">
  <div class="container">

    <h1 class="section-title">Upcoming Events</h1>

      <% @events.each do |event| %>
      <section class="event-index clear">
        <p class="event-date"><%= event.date %></p>
        <div class="event-info">
          <p class="event-name"><%= link_to event.name, event_path(event) %></p>
          <div class="time-location">
            <span class="event-time"><%= event.time %></span> :
            <span class="event-location"><%= event.location %></span>
          </div>
        </div>
      </section>
      <div class="action-links clear">
        <%= link_to 'Show', event %> |
        <%= link_to 'Edit', edit_event_path(event) %> |
       <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
      <% end %>
    
    <%= link_to 'New Event', new_event_path %>

  </div>
</section>

app/views/events/new.html.erb
<section class="container">

		<h1 class="section-title">New Event</h1>

		<%= render 'form' %>

		<%= link_to 'Back', events_path %>

</section>

app/views/events/show.html.erb
<section class="container">
  <div class="events">

    
    <div class="event-name"><%= @event.name %></div>
    

    <div>
      <span class="date"><%= @event.date %></span>
      <span class="time"><%= @event.time %></span>
    </div>
    
    <div>
      <%= @event.description %>
    </div>

    <% if present? %>
      <%= @event.image %>
    <% end %>

    <div>
      <%= link_to 'Edit', edit_event_path(@event) %> |
      <%= link_to 'Back', events_path %>
    </div>

  </div>
</section>

app/views/layouts/_header.html.erb
	<header class="header">
		<div class="container">
			<nav>
				<ul class="desktop-nav admin">
			    <li><%= link_to "Create events", new_event_path %></a></li>
			    <li><%= link_to "Create announcements", new_announcement_path %></li>
				</ul>
			</nav>
			<h1><%= link_to "Asbury Broadneck UMC", root_path, id: "brand" %></h1>
			<nav>
				<ul class="secondary-nav">
					<li><%= link_to "Tithe", new_charge_path, class: 'nav-link tithe-btn' %></li>
					<li><a href="#" class="primary-nav-trigger nav-link menu-text btn-open">Menu</a></li>
				</ul>
				<ul class="desktop-nav">
			    <li><a href="#">Sermons</a></li>
			    <li><%= link_to "Church events", events_path %></a></li>
			    <li><a href="#">About us</a></li>
			    <li><a href="#">Shop</a></li>
			    <li><a href="#">Contact us</a></li>
			    <li><%= link_to "Tithe here", new_charge_path %></li>
				</ul>
			</nav>
		</div>
	</header>

	<div class="overlay">
		<h1><%= link_to "Asbury Broadneck UMC", root_path, id: "brand" %></h1>
		<nav>
			<ul class="secondary-nav">
		    <li><a href="#" class="btn-close nav-link menu-text-close">Close</a></li>
		  </ul>
		</nav>
		<div class="container">
			<ul class="nav-wrap">
		    <li><a href="#">I'm new</a></li>
		    <li><a href="#">Sermons</a></li>
		    <li><%= link_to "Church events", events_path %></a></li>
		    <li><a href="#">Ministries</a></li>
		    <li><a href="#">Pastor's blog</a></li>
		    <li><a href="#">History</a></li>
		    <li><a href="#">About us</a></li>
		    <li><a href="#">Shop</a></li>
		    <li><a href="#">Contact us</a></li>
		    <li><%= link_to "Tithe here", new_charge_path %></li>
		    <li><a href="#">Facebook</a></li>
		    <li><a href="#">Twitter</a></li>
		    <li><a href="#">Instagram</a></li>
		  </ul>
		</div>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Asbury</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,800,700' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://checkout.stripe.com/checkout.js"></script>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<div class="notice">
		    <%= flash[:notice] %>
		  </div>
		  <div class="alert-div">
		    <%= flash[:alert] %>
		  </div>
		</div>

		<%= yield %>

	</body>
</html>

app/views/pages/home.html.erb
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="header-bg">
	<section class="page-header">
		<div class="container">
		  <div class="main-text-center-page">
		    <h1 class="main-greeting">Come to Church on Sunday</h1>
		    <p class="intro-text">Join us at Asbury Broadneck UMC and learn to grow with God and the community</p>
		    <div class="sunday-service">
		      <p class="center">Sunday School 9:00am</p>
		      <p class="center">Sunday Worship 10:15am</p>
		    </div>
		  </div>
		</div>
	</section>
</div>

<section class="announcements">
	<div class="container">
		<p><span class="announcements">Asbury announcements : </span>
		<% @announcements.each do |announcement| %>
			<%= link_to announcement.title, announcement_path(announcement) %>
		<% end %>
		</p>
	</div>
</section>

<section class="events">
	<div class="container">
		<h2 class="section-title">Church Events</h2>
		<% @events.each do |event| %>
		  <section class="event-show">
		    <p class="event-date"><%= event.date %></p>
		    <div class="event-info">
		      <p class="event-name"><%= link_to event.name, event_path(event) %></p>
		      <div class="time-location">
		        <span class="event-time"><%= event.time %></span> :
		        <span class="event-location"><%= event.location %></span>
		      </div>
		      <div class="clear"></div>
		    </div>
		  </section>
	 	<% end %>
	</div>
</section>

<section class="twitter-feed clear">
	<div class="container">
		<p><span class="announcements">Asbury tweets : </span>
		<% @announcements.each do |announcement| %>
			<%= link_to announcement.title, announcement_path(announcement) %>
		<% end %>
		</p>
	</div>
</section>

<section class="sermons">
	<div clas="container">
		<h2 class="section-title">Sermons</h2>
	</div>
</section>

app/views/pages/tithing.html.erb
<h1>Pages#tithing</h1>
<p>Find me in app/views/pages/tithing.html.erb</p>